name: github pages

on:
  push:
    branches:
    - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install yarn -g
    - run: yarn
    - run: yarn build:docs
    - run: yarn build:demo

    - name: Deploy gh-pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      env:
        ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        BRANCH: gh-pages 
        FOLDER: document-dist
      with:
          emptyCommits: false
