name: test

on:
  push:
    branches:
    - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install yarn -g
    - run: yarn
    - run: yarn test
